services:
  db:
    image: postgres:16-alpine
    container_name: mars-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: biospatial
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build: ./backend
    container_name: mars-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: node --watch server.js
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: biospatial
      DB_USER: postgres
      DB_PASSWORD: 1234
      NODE_OPTIONS: --max-old-space-size=4096
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
       

  frontend:
    build: ./frontend
    container_name: app_frontend
    ports:
      - "8080:80"   
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend/src:/usr/share/nginx/html:ro

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: