services:
  db:
    image: postgres:16-alpine
    container_name: mars-db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: biospatial
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: node:20
    container_name: mars-backend
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && node backend/server.js"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: biospatial
      DB_USER: postgres
      DB_PASSWORD: 1234
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: nginx
    container_name: mars-frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data: